# Site settings
title: Janhu's Blog
email: jacc_me@163.com
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: ""
url: ""
twitter_username: Janhu
github_username:  Janhu
facebook_username:  Janhu

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
